server:
  port: 8000
spring:
  application:
    name: alibaba-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
#        file-extension: yaml
